-- Typed models for the CompanySearch SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class NearPoint
---@field activite_principale? string
---@field activite_principale_naf25? string
---@field annee_categorie_entreprise? string
---@field annee_tranche_effectif_salarie? string
---@field caractere_employeur? string
---@field categorie_entreprise? string
---@field complements? table
---@field date_creation? string
---@field date_fermeture? string
---@field date_mise_a_jour? string
---@field date_mise_a_jour_insee? string
---@field date_mise_a_jour_rne? string
---@field dirigeants? table
---@field etat_administratif? string
---@field finances? table
---@field matching_etablissements? table
---@field nature_juridique? string
---@field nom_complet? string
---@field nom_raison_sociale? string
---@field nombre_etablissements? number
---@field nombre_etablissements_ouverts? number
---@field section_activite_principale? string
---@field siege? table
---@field sigle? string
---@field siren? string
---@field statut_diffusion? string
---@field tranche_effectif_salarie? string

---@class NearPointListMatch
---@field activite_principale? string
---@field include? string
---@field lat number
---@field limite_matching_etablissement? number
---@field long number
---@field minimal? boolean
---@field page? number
---@field page_etablissement? number
---@field per_page? number
---@field radius? number
---@field section_activite_principale? string
---@field sort_by_size? boolean

---@class Search
---@field activite_principale? string
---@field activite_principale_naf25? string
---@field annee_categorie_entreprise? string
---@field annee_tranche_effectif_salarie? string
---@field caractere_employeur? string
---@field categorie_entreprise? string
---@field complements? table
---@field date_creation? string
---@field date_fermeture? string
---@field date_mise_a_jour? string
---@field date_mise_a_jour_insee? string
---@field date_mise_a_jour_rne? string
---@field dirigeants? table
---@field etat_administratif? string
---@field finances? table
---@field matching_etablissements? table
---@field nature_juridique? string
---@field nom_complet? string
---@field nom_raison_sociale? string
---@field nombre_etablissements? number
---@field nombre_etablissements_ouverts? number
---@field section_activite_principale? string
---@field siege? table
---@field sigle? string
---@field siren? string
---@field statut_diffusion? string
---@field tranche_effectif_salarie? string

---@class SearchListMatch
---@field activite_principale? string
---@field ca_max? number
---@field ca_min? number
---@field categorie_entreprise? string
---@field code_collectivite_territoriale? string
---@field code_commune? string
---@field code_postal? string
---@field convention_collective_renseignee? boolean
---@field date_naissance_personne_max? string
---@field date_naissance_personne_min? string
---@field departement? string
---@field egapro_renseignee? boolean
---@field epci? string
---@field est_achats_responsable? boolean
---@field est_alim_confiance? boolean
---@field est_association? boolean
---@field est_bio? boolean
---@field est_collectivite_territoriale? boolean
---@field est_entrepreneur_individuel? boolean
---@field est_entrepreneur_spectacle? boolean
---@field est_ess? boolean
---@field est_finess? boolean
---@field est_l100_3? boolean
---@field est_organisme_formation? boolean
---@field est_patrimoine_vivant? boolean
---@field est_qualiopi? boolean
---@field est_rge? boolean
---@field est_service_public? boolean
---@field est_siae? boolean
---@field est_societe_mission? boolean
---@field est_uai? boolean
---@field etat_administratif? string
---@field id_convention_collective? string
---@field id_finess? string
---@field id_rge? string
---@field id_uai? string
---@field include? string
---@field limite_matching_etablissement? number
---@field minimal? boolean
---@field nature_juridique? string
---@field nom_personne? string
---@field page? number
---@field page_etablissement? number
---@field per_page? number
---@field prenoms_personne? string
---@field q? string
---@field region? string
---@field resultat_net_max? number
---@field resultat_net_min? number
---@field section_activite_principale? string
---@field sort_by_size? boolean
---@field tranche_effectif_salarie? string
---@field type_personne? string

local M = {}

return M
