-- Typed models for the CompanySearch SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class NearPoint
---@field activite_principale? string
---@field activite_principale_naf25? string
---@field annee_categorie_entreprise? string
---@field annee_tranche_effectif_salarie? string
---@field caractere_employeur? string
---@field categorie_entreprise? string
---@field complements? table
---@field date_creation? string
---@field date_fermeture? string
---@field date_mise_a_jour? string
---@field date_mise_a_jour_insee? string
---@field date_mise_a_jour_rne? string
---@field dirigeants? table
---@field etat_administratif? string
---@field finances? table
---@field matching_etablissements? table
---@field nature_juridique? string
---@field nom_complet? string
---@field nom_raison_sociale? string
---@field nombre_etablissements? number
---@field nombre_etablissements_ouverts? number
---@field section_activite_principale? string
---@field siege? table
---@field sigle? string
---@field siren? string
---@field statut_diffusion? string
---@field tranche_effectif_salarie? string

---@class NearPointListMatch
---@field activite_principale? string
---@field activite_principale_naf25? string
---@field annee_categorie_entreprise? string
---@field annee_tranche_effectif_salarie? string
---@field caractere_employeur? string
---@field categorie_entreprise? string
---@field complements? table
---@field date_creation? string
---@field date_fermeture? string
---@field date_mise_a_jour? string
---@field date_mise_a_jour_insee? string
---@field date_mise_a_jour_rne? string
---@field dirigeants? table
---@field etat_administratif? string
---@field finances? table
---@field matching_etablissements? table
---@field nature_juridique? string
---@field nom_complet? string
---@field nom_raison_sociale? string
---@field nombre_etablissements? number
---@field nombre_etablissements_ouverts? number
---@field section_activite_principale? string
---@field siege? table
---@field sigle? string
---@field siren? string
---@field statut_diffusion? string
---@field tranche_effectif_salarie? string

---@class Search
---@field activite_principale? string
---@field activite_principale_naf25? string
---@field annee_categorie_entreprise? string
---@field annee_tranche_effectif_salarie? string
---@field caractere_employeur? string
---@field categorie_entreprise? string
---@field complements? table
---@field date_creation? string
---@field date_fermeture? string
---@field date_mise_a_jour? string
---@field date_mise_a_jour_insee? string
---@field date_mise_a_jour_rne? string
---@field dirigeants? table
---@field etat_administratif? string
---@field finances? table
---@field matching_etablissements? table
---@field nature_juridique? string
---@field nom_complet? string
---@field nom_raison_sociale? string
---@field nombre_etablissements? number
---@field nombre_etablissements_ouverts? number
---@field section_activite_principale? string
---@field siege? table
---@field sigle? string
---@field siren? string
---@field statut_diffusion? string
---@field tranche_effectif_salarie? string

---@class SearchListMatch
---@field activite_principale? string
---@field activite_principale_naf25? string
---@field annee_categorie_entreprise? string
---@field annee_tranche_effectif_salarie? string
---@field caractere_employeur? string
---@field categorie_entreprise? string
---@field complements? table
---@field date_creation? string
---@field date_fermeture? string
---@field date_mise_a_jour? string
---@field date_mise_a_jour_insee? string
---@field date_mise_a_jour_rne? string
---@field dirigeants? table
---@field etat_administratif? string
---@field finances? table
---@field matching_etablissements? table
---@field nature_juridique? string
---@field nom_complet? string
---@field nom_raison_sociale? string
---@field nombre_etablissements? number
---@field nombre_etablissements_ouverts? number
---@field section_activite_principale? string
---@field siege? table
---@field sigle? string
---@field siren? string
---@field statut_diffusion? string
---@field tranche_effectif_salarie? string

local M = {}

return M
