# CompanySearch SDK configuration

module CompanySearchConfig
  def self.make_config
    {
      "main" => {
        "name" => "CompanySearch",
      },
      "feature" => {
        "test" => {
          "options" => {
            "active" => false,
          },
        },
      },
      "options" => {
        "base" => "https://recherche-entreprises.api.gouv.fr",
        "auth" => {
          "prefix" => "Bearer",
        },
        "headers" => {
          "content-type" => "application/json",
        },
        "entity" => {
          "near_point" => {},
          "search" => {},
        },
      },
      "entity" => {
        "near_point" => {
          "fields" => [
            {
              "name" => "activite_principale",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 0,
            },
            {
              "name" => "activite_principale_naf25",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 1,
            },
            {
              "name" => "annee_categorie_entreprise",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 2,
            },
            {
              "name" => "annee_tranche_effectif_salarie",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 3,
            },
            {
              "name" => "caractere_employeur",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 4,
            },
            {
              "name" => "categorie_entreprise",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 5,
            },
            {
              "name" => "complement",
              "req" => false,
              "type" => "`$OBJECT`",
              "active" => true,
              "index$" => 6,
            },
            {
              "name" => "date_creation",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 7,
            },
            {
              "name" => "date_fermeture",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 8,
            },
            {
              "name" => "date_mise_a_jour",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 9,
            },
            {
              "name" => "date_mise_a_jour_insee",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 10,
            },
            {
              "name" => "date_mise_a_jour_rne",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 11,
            },
            {
              "name" => "dirigeant",
              "req" => false,
              "type" => "`$ARRAY`",
              "active" => true,
              "index$" => 12,
            },
            {
              "name" => "etat_administratif",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 13,
            },
            {
              "name" => "finance",
              "req" => false,
              "type" => "`$OBJECT`",
              "active" => true,
              "index$" => 14,
            },
            {
              "name" => "matching_etablissement",
              "req" => false,
              "type" => "`$ARRAY`",
              "active" => true,
              "index$" => 15,
            },
            {
              "name" => "nature_juridique",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 16,
            },
            {
              "name" => "nom_complet",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 17,
            },
            {
              "name" => "nom_raison_sociale",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 18,
            },
            {
              "name" => "nombre_etablissement",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 19,
            },
            {
              "name" => "nombre_etablissements_ouvert",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 20,
            },
            {
              "name" => "section_activite_principale",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 21,
            },
            {
              "name" => "siege",
              "req" => false,
              "type" => "`$OBJECT`",
              "active" => true,
              "index$" => 22,
            },
            {
              "name" => "sigle",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 23,
            },
            {
              "name" => "siren",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 24,
            },
            {
              "name" => "statut_diffusion",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 25,
            },
            {
              "name" => "tranche_effectif_salarie",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 26,
            },
          ],
          "name" => "near_point",
          "op" => {
            "list" => {
              "name" => "list",
              "points" => [
                {
                  "args" => {
                    "query" => [
                      {
                        "example" => "01.12Z,28.15Z",
                        "kind" => "query",
                        "name" => "activite_principale",
                        "orig" => "activite_principale",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "siege,complements",
                        "kind" => "query",
                        "name" => "include",
                        "orig" => "include",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "lat",
                        "orig" => "lat",
                        "reqd" => true,
                        "type" => "`$NUMBER`",
                        "active" => true,
                      },
                      {
                        "example" => 10,
                        "kind" => "query",
                        "name" => "limite_matching_etablissement",
                        "orig" => "limite_matching_etablissement",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "long",
                        "orig" => "long",
                        "reqd" => true,
                        "type" => "`$NUMBER`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "minimal",
                        "orig" => "minimal",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "example" => 1,
                        "kind" => "query",
                        "name" => "page",
                        "orig" => "page",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "example" => 1,
                        "kind" => "query",
                        "name" => "page_etablissement",
                        "orig" => "page_etablissement",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "example" => 10,
                        "kind" => "query",
                        "name" => "per_page",
                        "orig" => "per_page",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "example" => 5,
                        "kind" => "query",
                        "name" => "radius",
                        "orig" => "radius",
                        "reqd" => false,
                        "type" => "`$NUMBER`",
                        "active" => true,
                      },
                      {
                        "example" => "A,J,U",
                        "kind" => "query",
                        "name" => "section_activite_principale",
                        "orig" => "section_activite_principale",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "sort_by_size",
                        "orig" => "sort_by_size",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/near_point",
                  "parts" => [
                    "near_point",
                  ],
                  "select" => {
                    "exist" => [
                      "activite_principale",
                      "include",
                      "lat",
                      "limite_matching_etablissement",
                      "long",
                      "minimal",
                      "page",
                      "page_etablissement",
                      "per_page",
                      "radius",
                      "section_activite_principale",
                      "sort_by_size",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "active" => true,
                  "index$" => 0,
                },
              ],
              "input" => "data",
              "key$" => "list",
            },
          },
          "relations" => {
            "ancestors" => [],
          },
        },
        "search" => {
          "fields" => [
            {
              "name" => "activite_principale",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 0,
            },
            {
              "name" => "activite_principale_naf25",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 1,
            },
            {
              "name" => "annee_categorie_entreprise",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 2,
            },
            {
              "name" => "annee_tranche_effectif_salarie",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 3,
            },
            {
              "name" => "caractere_employeur",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 4,
            },
            {
              "name" => "categorie_entreprise",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 5,
            },
            {
              "name" => "complement",
              "req" => false,
              "type" => "`$OBJECT`",
              "active" => true,
              "index$" => 6,
            },
            {
              "name" => "date_creation",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 7,
            },
            {
              "name" => "date_fermeture",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 8,
            },
            {
              "name" => "date_mise_a_jour",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 9,
            },
            {
              "name" => "date_mise_a_jour_insee",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 10,
            },
            {
              "name" => "date_mise_a_jour_rne",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 11,
            },
            {
              "name" => "dirigeant",
              "req" => false,
              "type" => "`$ARRAY`",
              "active" => true,
              "index$" => 12,
            },
            {
              "name" => "etat_administratif",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 13,
            },
            {
              "name" => "finance",
              "req" => false,
              "type" => "`$OBJECT`",
              "active" => true,
              "index$" => 14,
            },
            {
              "name" => "matching_etablissement",
              "req" => false,
              "type" => "`$ARRAY`",
              "active" => true,
              "index$" => 15,
            },
            {
              "name" => "nature_juridique",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 16,
            },
            {
              "name" => "nom_complet",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 17,
            },
            {
              "name" => "nom_raison_sociale",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 18,
            },
            {
              "name" => "nombre_etablissement",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 19,
            },
            {
              "name" => "nombre_etablissements_ouvert",
              "req" => false,
              "type" => "`$INTEGER`",
              "active" => true,
              "index$" => 20,
            },
            {
              "name" => "section_activite_principale",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 21,
            },
            {
              "name" => "siege",
              "req" => false,
              "type" => "`$OBJECT`",
              "active" => true,
              "index$" => 22,
            },
            {
              "name" => "sigle",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 23,
            },
            {
              "name" => "siren",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 24,
            },
            {
              "name" => "statut_diffusion",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 25,
            },
            {
              "name" => "tranche_effectif_salarie",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 26,
            },
          ],
          "name" => "search",
          "op" => {
            "list" => {
              "name" => "list",
              "points" => [
                {
                  "args" => {
                    "query" => [
                      {
                        "example" => "01.12Z,28.15Z",
                        "kind" => "query",
                        "name" => "activite_principale",
                        "orig" => "activite_principale",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => 100000,
                        "kind" => "query",
                        "name" => "ca_max",
                        "orig" => "ca_max",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "example" => 100000,
                        "kind" => "query",
                        "name" => "ca_min",
                        "orig" => "ca_min",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "example" => "PME",
                        "kind" => "query",
                        "name" => "categorie_entreprise",
                        "orig" => "categorie_entreprise",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "75C",
                        "kind" => "query",
                        "name" => "code_collectivite_territoriale",
                        "orig" => "code_collectivite_territoriale",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "01247,01111",
                        "kind" => "query",
                        "name" => "code_commune",
                        "orig" => "code_commune",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "38540,38189",
                        "kind" => "query",
                        "name" => "code_postal",
                        "orig" => "code_postal",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "convention_collective_renseignee",
                        "orig" => "convention_collective_renseignee",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "example" => "1990-01-01",
                        "kind" => "query",
                        "name" => "date_naissance_personne_max",
                        "orig" => "date_naissance_personne_max",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "1960-01-01",
                        "kind" => "query",
                        "name" => "date_naissance_personne_min",
                        "orig" => "date_naissance_personne_min",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "02,89",
                        "kind" => "query",
                        "name" => "departement",
                        "orig" => "departement",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "egapro_renseignee",
                        "orig" => "egapro_renseignee",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "example" => "200058519,248100737",
                        "kind" => "query",
                        "name" => "epci",
                        "orig" => "epci",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_achats_responsable",
                        "orig" => "est_achats_responsable",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_alim_confiance",
                        "orig" => "est_alim_confiance",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_association",
                        "orig" => "est_association",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_bio",
                        "orig" => "est_bio",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_collectivite_territoriale",
                        "orig" => "est_collectivite_territoriale",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_entrepreneur_individuel",
                        "orig" => "est_entrepreneur_individuel",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_entrepreneur_spectacle",
                        "orig" => "est_entrepreneur_spectacle",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_ess",
                        "orig" => "est_ess",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_finess",
                        "orig" => "est_finess",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_l100_3",
                        "orig" => "est_l100_3",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_organisme_formation",
                        "orig" => "est_organisme_formation",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_patrimoine_vivant",
                        "orig" => "est_patrimoine_vivant",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_qualiopi",
                        "orig" => "est_qualiopi",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_rge",
                        "orig" => "est_rge",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_service_public",
                        "orig" => "est_service_public",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_siae",
                        "orig" => "est_siae",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_societe_mission",
                        "orig" => "est_societe_mission",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "est_uai",
                        "orig" => "est_uai",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "etat_administratif",
                        "orig" => "etat_administratif",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "1090",
                        "kind" => "query",
                        "name" => "id_convention_collective",
                        "orig" => "id_convention_collective",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "010003853",
                        "kind" => "query",
                        "name" => "id_finess",
                        "orig" => "id_finess",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "8611M10D109",
                        "kind" => "query",
                        "name" => "id_rge",
                        "orig" => "id_rge",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "0022004T",
                        "kind" => "query",
                        "name" => "id_uai",
                        "orig" => "id_uai",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "siege,complements",
                        "kind" => "query",
                        "name" => "include",
                        "orig" => "include",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => 10,
                        "kind" => "query",
                        "name" => "limite_matching_etablissement",
                        "orig" => "limite_matching_etablissement",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "minimal",
                        "orig" => "minimal",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "example" => "7344,6544",
                        "kind" => "query",
                        "name" => "nature_juridique",
                        "orig" => "nature_juridique",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "Dupont",
                        "kind" => "query",
                        "name" => "nom_personne",
                        "orig" => "nom_personne",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => 1,
                        "kind" => "query",
                        "name" => "page",
                        "orig" => "page",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "example" => 1,
                        "kind" => "query",
                        "name" => "page_etablissement",
                        "orig" => "page_etablissement",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "example" => 10,
                        "kind" => "query",
                        "name" => "per_page",
                        "orig" => "per_page",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "example" => "Monsieur",
                        "kind" => "query",
                        "name" => "prenoms_personne",
                        "orig" => "prenoms_personne",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "q",
                        "orig" => "q",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "11,76",
                        "kind" => "query",
                        "name" => "region",
                        "orig" => "region",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => 100000,
                        "kind" => "query",
                        "name" => "resultat_net_max",
                        "orig" => "resultat_net_max",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "example" => 100000,
                        "kind" => "query",
                        "name" => "resultat_net_min",
                        "orig" => "resultat_net_min",
                        "reqd" => false,
                        "type" => "`$INTEGER`",
                        "active" => true,
                      },
                      {
                        "example" => "A,J,U",
                        "kind" => "query",
                        "name" => "section_activite_principale",
                        "orig" => "section_activite_principale",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "sort_by_size",
                        "orig" => "sort_by_size",
                        "reqd" => false,
                        "type" => "`$BOOLEAN`",
                        "active" => true,
                      },
                      {
                        "example" => "NN,00,01",
                        "kind" => "query",
                        "name" => "tranche_effectif_salarie",
                        "orig" => "tranche_effectif_salarie",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "type_personne",
                        "orig" => "type_personne",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/search",
                  "parts" => [
                    "search",
                  ],
                  "select" => {
                    "exist" => [
                      "activite_principale",
                      "ca_max",
                      "ca_min",
                      "categorie_entreprise",
                      "code_collectivite_territoriale",
                      "code_commune",
                      "code_postal",
                      "convention_collective_renseignee",
                      "date_naissance_personne_max",
                      "date_naissance_personne_min",
                      "departement",
                      "egapro_renseignee",
                      "epci",
                      "est_achats_responsable",
                      "est_alim_confiance",
                      "est_association",
                      "est_bio",
                      "est_collectivite_territoriale",
                      "est_entrepreneur_individuel",
                      "est_entrepreneur_spectacle",
                      "est_ess",
                      "est_finess",
                      "est_l100_3",
                      "est_organisme_formation",
                      "est_patrimoine_vivant",
                      "est_qualiopi",
                      "est_rge",
                      "est_service_public",
                      "est_siae",
                      "est_societe_mission",
                      "est_uai",
                      "etat_administratif",
                      "id_convention_collective",
                      "id_finess",
                      "id_rge",
                      "id_uai",
                      "include",
                      "limite_matching_etablissement",
                      "minimal",
                      "nature_juridique",
                      "nom_personne",
                      "page",
                      "page_etablissement",
                      "per_page",
                      "prenoms_personne",
                      "q",
                      "region",
                      "resultat_net_max",
                      "resultat_net_min",
                      "section_activite_principale",
                      "sort_by_size",
                      "tranche_effectif_salarie",
                      "type_personne",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "active" => true,
                  "index$" => 0,
                },
              ],
              "input" => "data",
              "key$" => "list",
            },
          },
          "relations" => {
            "ancestors" => [],
          },
        },
      },
    }
  end


  def self.make_feature(name)
    require_relative 'features'
    CompanySearchFeatures.make_feature(name)
  end
end
